[package]
name = "mass-heif-convert"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { version = "1.0", features = ["backtrace"] }
indexmap = "2.1"
once_cell = "1.18"
camino = "1.1"
png = "0.17"
libheif-rs = "0.22"
termion = "2.0"

tokio = { version = "1", features = ["full"] }
